name: Project is releasable

on:
    push:
        branches:
            - master

jobs:
    release:
        name: Release a new version
        runs-on: ubuntu-latest
        steps:
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y make
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '12'
            - name: Install dependencies
              run: yarn install
            - name: Make all dist files
              run: make build
            - name: Release a new version
              run: make release
              env:
                  GH_TOKEN: ${{secrets.GH_TOKEN}}
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
            - name: Push new tags
              run: git push --follow-tags
