name: Project is releasable

on:
    push:
        branches:
            - master

jobs:
    release:
        name: Release a new version
        environment: Release
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        steps:
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y make
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '12'
            - name: Install yarn
              run: npm i -g yarn
            - name: Install all dependencies
              run: yarn install
            - name: Release a new version
              run: make release
              env:
                  GH_TOKEN: ${{secrets.GH_TOKEN}}
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
