name: Project is testable

on: [push]

jobs:
    packagaya:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '15.x'
            - name: Install yarn
              run: npm i -g yarn
            - run: yarn add -W -D @packagaya/ts-adapter
            - run: cd packages/apps/cli && yarn run build
            - run: yarn global add @packagaya/cli
            - run: $(yarn global bin)/packagaya sync info

    tests:
        name: Testing project
        runs-on: ubuntu-latest
        needs: [packagaya]
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        strategy:
            matrix:
                node-version: [13.x, 14.x, 15.x]
        steps:
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y make
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install yarn
              run: npm i -g yarn
            - name: Install all dependencies
              run: make install
            - name: Test the source code
              run: make test
