name: Project is testable

on: [push]

jobs:
    test:
        name: Testing project
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [13.x, 14.x, 15.x]
        steps:
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y make
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make test
